config/routes.rb
Rails.application.routes.draw do
  resources :store, only: [:index]
  resources :products
  resources :order_items, only: [:create, :update, :destroy]
  resource :cart, only: [:show]
  resources :orders

  get 'store/index'
  get 'order_items/create'
  get 'order_items/update'
  get 'order_items/destroy'
  get 'order/new'
  get 'carts/show'

  root 'store#index'

end

app/models/order.rb
class Order < ActiveRecord::Base
  
  belongs_to :order_status
  has_many :order_items, dependent: :destroy
  before_create :set_order_status

  # before_updatevalidates :buyer_email, :shipping_address, presence: true

  def total
  	order_items.collect { |order_item| order_item.subtotal }.sum
  end

private

  def set_order_status
  	self.order_status_id = 1
  end

end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base

  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }

  def subtotal
    valid? ? (quantity * unit_price) : 0
  end

  def unit_price
    product.price
  end

end

app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
  
  has_many :orders

end

app/models/product.rb
class Product < ActiveRecord::Base

  has_many :order_items

  before_destroy :ensure_not_referenced_by_any_order_item

  validates :name, uniqueness: true
  validates :name, :description, :image_url, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 1 }
  validates :image_url, format: {
    with: %r{\.(gif|jpg|png)\z}i,
    message: 'must be a URL for GIF, JPG or PNG image'
  }

  private

    def ensure_not_referenced_by_any_order_item
      if order_items.empty?
        return true
      else
        errors.add(:base, 'Order Items present.')
        return false
      end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_order

  def current_order
  	if session[:order_id]
      Order.find(session[:order_id])
    else
      Order.new
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
  	@order_items = current_order.order_items
  end

end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  
  def create
    @order = current_order
    @order_item = @order.order_items.new(order_item_params)
    @order.save
    session[:order_id] = @order.id
  end

  def update
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.update_attributes(order_item_params)
    @order_items = @order.order_items
  end

  def destroy
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.destroy
    @order_items = @order.order_items
  end

  private

    def order_item_params
      params.require(:order_item).permit(:quantity, :product_id)
    end
    
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:new, :show, :create, :update]

  def new
    @order = Order.new
  end

  def show
  end

  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
      else
        format.html { render :new }
      end
    end

  end

  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully processed.' }
      else
        format.html { render :edit }
      end
    end
  end

  private

    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:buyer_email, :shipping_address, :total)
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    @order_item = current_order.order_items.new
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :price)
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController

  def index
  	@products = Product.all
  	@order_item = current_order.order_items.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/carts/_cart_row.html.erb
<div class="well well-sm">
  <div class="row">
    <div class="col-xs-8">
      <h4><%= product.name %></h4>
    </div>
    <div class="col-xs-4">
      
      <%= form_for order_item, remote: true do |f| %>
        <div class="row">
          <div class="col-xs-4">
            <%= f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1 %>
            <%= f.hidden_field :product_id, value: product.id %>
          </div>
          <div class="col-xs-8 text-right">
            <div class="btn-group">
              <%= f.submit "Update Quantity", class: "btn btn-default" %>
              <%= link_to "Delete", order_item, { data: { confirm: "Are you sure you wish to delete the product '#{order_item.product.name}' from your cart?" }, method: :delete, remote: true, class: "btn btn-warning" } %>
            </div>
          </div>
        </div>
        <h6 class="text-right">Unit Price: <%= number_to_currency order_item.unit_price %></h6>
        <h5 class="text-right">Total Price: <%= number_to_currency order_item.subtotal %></h5>
      <% end %>
    
    </div>   
  </div>
</div>

app/views/carts/_shopping_cart.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
  <div class="alert alert-danger" ="alert">
    <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<% if @order_items.size == 0 %>
  <p class="text-center">
    There are no items in your shopping cart.  Please <%= link_to "go back", root_path %> and add some items to your cart.
  </p>
<% else %>
  <% @order_items.each do |order_item| %>
    <%= render 'carts/cart_row', product: order_item.product, order_item: order_item, show_total: true %>
  <% end %>

  <div class="checkout text-right">
    <hr>
    <h3><span class="price">Total: <%= number_to_currency current_order.total %></span></h3>
    <%= button_to "Checkout", new_order_path, method: :get, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/carts/show.html.erb
<div class="shopping-cart">
  <%= render "shopping_cart" %>
</div>

app/views/layouts/_cart_text.html.erb
<%= "(#{current_order.order_items.size})" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BY MARILIA DIAS</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

    <!-- Navigation -->
  <nav class="navbar navbar-inverse navbar-static-top" role="navigation">
    <div class="container-fluid">
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">  
        <form class="navbar-form navbar-left" role="search">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search" aria-describedby="basic-addon2">
            <span class="input-group-addon" id="basic-addon2">
              <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
            </span>
          </div>
        </form>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to 'HOME', root_path %>
          </li>
          <li>
            <%= link_to 'PRODUCTS', controller: 'products' %>
          </li>
          <li>
            <a href="#">TRACK ORDER</a>
          </li>  
          <li>
            <%= link_to cart_path do %>
              <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>
              <span class="cart-size"><span class="cart-text"><%= render 'layouts/cart_text' %></span></span>
            <% end %>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.navbar-collapse -->
  </nav>

  <div class="logo row text-center">
    <!-- Jumbotron Header -->
    <header class="jumbotron">
      <h1><%= link_to "PALAVRA DE NADA", root_path %></h1>
    </header>

    <hr>

  </div>

  <body class="<%= controller.controller_name %>">
    <!-- Page Content -->
    <div class="container">
      <div class="row text-center">
        <%= yield %>
      </div>
    </div>
    <!-- /.container -->
  
  </body>

  <div class="footer text-center">
    <h5>Developed by <a href="laisvarejao.github.io">Lais Varejão</a></h5>
    <span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
  </div>

</html>

app/views/order_items/create.js.erb
<% if @order_item.errors.any? %>
alert("not valid.")
<% else %>
  $(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
<% end %>

app/views/order_items/destroy.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")

app/views/order_items/update.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-md-6 col-md-offset-3">
    <div class="field">
      <%= f.label :buyer_email %><br>
      <%= f.text_field :buyer_email, class: "form-control" %>
    </div>
    <div class="field">
      <%= f.label :shipping_address %><br>
      <%= f.text_area :shipping_address, class: "form-control" %>
    </div>
    <div class="field">
      <hr>
      <%= f.hidden_field :total, :value => current_order.total %>
      <h3><span class="price">Total: <%= number_to_currency current_order.total %></span></h3>
    </div>  
    <div class="actions">
      <%= f.submit class: 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/orders/new.html.erb
<h1>Order</h1>

<%= render 'form' %>

<div class="col-md-6 col-md-offset-3">
  <%= link_to 'Back', cart_path %>
</div>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Buyer:</strong>
  <%= @order.buyer_email %>
</p>

<p>
  <strong>Shipping Address:</strong>
  <%= @order.shipping_address %>
</p>

<p>
  <strong>Total:</strong>
  <%= @order.total %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', root_path %>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-md-6 col-md-offset-3">
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description, class: "form-control" %>
    </div>
    <div class="field">
      <%= f.label :image_url %><br>
      <%= f.text_field :image_url, class: "form-control" %>
    </div>
    <div class="field">
        <%= f.label :price %><br>
        <%= f.text_field :price, class: "form-control" %>
    </div>
    <div class="actions">
      <%= f.submit class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/products/_product_row.html.erb
<div class="col-md-3 col-sm-6">
      <div class="thumbnail">
          <%= image_tag(product.image_url) %>
          <div class="caption">

            <span class="text-left">
              <h3><%= product.name %></h3>
            </span>

              <%= form_for order_item, remote: true do |f| %>
              <h3 class="text-right"><span class="price"><%= number_to_currency product.price %></span></h3>
                <div class="input-group">
                  <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
                  <div class="input-group-btn">
                    <%= f.hidden_field :product_id, value: product.id %>
                    <%= f.submit "Add to Cart", class: "btn btn-warning" %>
                  </div>
                </div>
              <% end %>
          </div>
      </div>
  </div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<div class="col-md-6 col-md-offset-3">
	<%= link_to 'Show', @product %> |
	<%= link_to 'Back', products_path %>
</div>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<!-- Title -->
<div class="col-lg-12">
    <h3>PRODUCTS</h3>
  </div>
</div>

<%= link_to 'New Product', new_product_path, class: "btn pull-right btn-default" %>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Image url</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.image_url %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<div class="col-md-6 col-md-offset-3">
  <%= link_to 'Back', products_path %>
</div>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/store/index.html.erb
<!-- Page Features -->
  <!-- Title -->
<div class="row">
  <div class="col-lg-12">
    <h3>CARDS</h3>
  </div>
</div>

<div class="row">

<% @products.each do |product| %>
  <%= render "products/product_row", product: product, order_item: @order_item %>
<% end %>

</div>
<!-- /.row -->

<hr>